version: 0.2 
 
phases: 
  install: 
    runtime-versions: 
      docker: 18 
  pre_build: 
    commands: 
      - echo Logging in to Amazon ECR... 
      - aws --version 
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email) 
      - REPOSITORY_URI=665934528137.dkr.ecr.us-east-1.amazonaws.com/springworksproject 
  build: 
    commands: 
      - echo Build started on `date` 
      - echo Building the Docker image...           
      - docker build -t $REPOSITORY_URI . 
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest 
  post_build: 
    commands: 
      - echo Build completed on `date` 
      - echo Pushing the Docker images... 
      - docker push $REPOSITORY_URI:latest 
      - echo Writing image definitions file... 
      - printf '[{"name":"springworksproject","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json 
artifacts: 
    files: imagedefinitions.json 
      
