version: 0.2


phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - docker build -t springworksproject .
      - docker tag springworksproject:latest 665934528137.dkr.ecr.us-east-1.amazonaws.com/springworksproject:latest
  post_build:
    commands:
      - docker push 665934528137.dkr.ecr.us-east-1.amazonaws.com/springworksproject:latest
      
